{% set version = "2.1.5" %}
{% set sha256 = "29726e72f65cf2d8a3c183d858ce497ddc26cb1c9e09957f109da09669d3f718" %}

package:
  name: diamond
  version: {{ version }}

source:
  url: https://github.com/bbuchfink/diamond/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - boost-cpp
    - zlib
  run:
    - boost-cpp
    - zlib

test:
  commands:
    - diamond --help 2>&1 > /dev/null

about:
  home: https://github.com/bbuchfink/diamond
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: Accelerated BLAST compatible local sequence aligner

extra:
  identifiers:
    - biotools:Diamond
    - doi:10.1038/nmeth.3176
