{% set version = "1.0.1" %}

package:
  name: nthits
  version: {{ version }}

source:
  url: https://github.com/bcgsc/ntHits/archive/v{{ version }}.tar.gz
  sha256: a7f47e9e908562ccaf514ebd75fc581cc2c2cfa997edb361cf0d29c399b43090

build:
  number: 0

requirements:
  build:
    - make
    - automake
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  run:
    - llvm-openmp  # [osx]

test:
  commands:
    - nthits --help

about:
  home: https://github.com/bcgsc/ntHits
  license: MIT
  license_file: LICENSE
  summary: a method for identifying repeats in high-throughput DNA sequencing data.
